### PR TITLE
Update plugin structure

### PR DESCRIPTION
**Pull request by ErCollao**
I've made the changes so that the project follows the same structure that you'd get if you follow the latest rails plugin guide (https://guides.rubyonrails.org/plugins.html).

It also inlcludes a draft gemspec to publish it. I didn't know if I should add you @gnapse, or if we should both take care of it (or if you want me to take care of it). So at the moment there's both of us, but I'm happy with any change!

### CODE REVIEW

**Comment by gnapse** [comment]
I’m not sure what you mean with who “takes care of it”. You mean publishing? I’m more than happy to let you take the lead on that. And if you’re going to need this and are willing to maintain it I can even give you direct write access to the repo and make you a collaborator.

As for this PR, is it ready to be merged?

**Comment by ErCollao** [comment]
I meant publishing it as at RubyGems, yes 😄 In that case, I'll take the lead as soon as I have some time. Thanks!

As for the PR, it works on my app when I add it as a gem, so I'd say it's ready. It doesn't have tests yet (maybe my next step), so that's all I can say for sure!

**Comment by gnapse** [comment]
> it works on my app when I add it as a gem, so I'd say it's ready

Great! BTW, I made you collaborator, so you can clone this repo and push PRs against it. You should also be able to approve PRs, either yours of from other contributors. I'll still be around and watching the repo, but I don't want to become a bottleneck if you continue to contribute to it (or even others).

**Comment by ErCollao** [comment]
Excellent, thanks @gnapse !

**Pull request merged**
